In [55]:
from nba_api.stats.static import players
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
pd.set_option('display.max_rows', 10)

# Get all players from nba_api and store in variable
playerList = players.get_players()

In [56]:
players_df = pd.DataFrame(playerList)
players_df

           id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False
...       ...                  ...        ...           ...        ...
4496  1627790           Ante Zizic       Ante         Zizic       True
4497    78647             Jim Zoet        Jim          Zoet      False
4498    78648            Bill Zopf       Bill          Zopf      False
4499  1627826          Ivica Zubac      Ivica         Zubac       True
4500    78650           Matt Zunic       Matt         Zunic      False

[4501 rows x 5 columns]

In [57]:
# cut down list to contain only ACTIVE players
act_df = players_df.loc[players_df["is_active"]==True]
act_df

,id,full_name,first_name,last_name,is_active
21,203500,Steven Adams,Steven,Adams,True
23,1628389,Bam Adebayo,Bam,Adebayo,True
41,200746,LaMarcus Aldridge,LaMarcus,Aldridge,True
48,1629734,Kyle Alexander,Kyle,Alexander,True
50,1629638,Nickeil Alexander-Walker,Nickeil,Alexander-Walker,True
...,...,...,...,...,...
4477,201152,Thaddeus Young,Thaddeus,Young,True
4479,1629027,Trae Young,Trae,Young,True
4482,203469,Cody Zeller,Cody,Zeller,True
4496,1627790,Ante Zizic,Ante,Zizic,True
4499,1627826,Ivica Zubac,Ivica,Zubac,True

In [58]:
# condensing DF to name/active status
act_df2 = act_df[["full_name","is_active"]]
act_df3 = act_df2.rename(columns={"full_name":"Player"})
act_df3

                        Player  is_active
21                Steven Adams       True
23                 Bam Adebayo       True
41           LaMarcus Aldridge       True
48              Kyle Alexander       True
50    Nickeil Alexander-Walker       True
...                        ...        ...
4477            Thaddeus Young       True
4479                Trae Young       True
4482               Cody Zeller       True
4496                Ante Zizic       True
4499               Ivica Zubac       True

[519 rows x 2 columns]

In [59]:
# act_df.to_csv("active_players.csv")

In [60]:
#Reading in xlsx file to dataframe
workbook = "2016-2020 Advanced Player Stats.xlsx"
all_dfs = pd.read_excel(workbook, sheet_name = None)

# concatonating all sheets into single DF
ps_df = pd.concat(all_dfs, ignore_index = True)
# dropping NaN columns
ps_df.dropna(axis=1, how = "all")

,Rank (WS),Player,Year,Pos,Age,Tm,G,MP,PER,TS%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,1,Stephen Curry,2016,PG,27,GSW,79,2700,31.5,0.669,...,12.9,32.6,13.8,4.1,17.9,0.318,10.3,1.6,11.9,9.5
1,2,Kevin Durant,2016,SF,27,OKC,72,2578,28.2,0.634,...,13.5,30.6,11.0,3.5,14.5,0.270,8.4,1.6,9.9,7.8
2,3,Russell Westbrook,2016,PG,27,OKC,80,2750,27.6,0.554,...,16.8,31.6,10.0,4.0,14.0,0.245,6.4,1.4,7.8,6.8
3,4,Kawhi Leonard,2016,SF,24,SAS,72,2380,26.0,0.616,...,7.8,25.8,8.3,5.5,13.7,0.277,6.1,3.0,9.1,6.7
4,5,LeBron James,2016,SF,31,CLE,76,2709,27.5,0.588,...,13.2,31.4,9.6,4.0,13.6,0.242,7.0,2.0,9.0,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,510,Theo Pinson,2020,SG,24,BRK,33,365,5.2,0.370,...,16.9,22.4,-1.0,0.5,-0.6,-0.074,-6.9,-0.2,-7.1,-0.5
2542,511,Dwayne Bacon,2020,SG,24,CHO,39,687,6.1,0.419,...,12.2,19.5,-1.2,0.4,-0.8,-0.053,-5.9,-0.9,-6.8,-0.8
2543,512,Dennis Smith Jr.,2020,PG,22,NYK,34,537,7.5,0.399,...,19.8,23.1,-1.3,0.5,-0.9,-0.079,-5.2,-0.9,-6.1,-0.6
2544,513,Jordan Poole,2020,SG,20,GSW,57,1274,7.2,0.454,...,11.8,21.1,-1.6,0.4,-1.2,-0.047,-4.4,-2.2,-6.6,-1.5
2545,514,Darius Garland,2020,PG,20,CLE,59,1824,8.5,0.498,...,17.1,20.7,-1.3,0.0,-1.3,-0.035,-2.7,-2.9,-5.6,-1.7

In [62]:
merged_ps = pd.merge(act_df3,ps_df,on="Player",how="outer")
merged_ps

,Player,is_active,Rank (WS),Year,Pos,Age,Tm,G,MP,PER,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Steven Adams,True,44.0,2016.0,C,22.0,OKC,80.0,2014.0,15.5,...,14.1,12.6,4.2,2.3,6.5,0.155,0.0,0.2,0.2,1.1
1,Steven Adams,True,47.0,2017.0,C,23.0,OKC,80.0,2389.0,16.5,...,16.0,16.2,3.3,3.1,6.5,0.130,-0.2,0.0,-0.2,1.1
2,Steven Adams,True,15.0,2018.0,C,24.0,OKC,76.0,2487.0,20.6,...,13.3,16.7,6.7,3.0,9.7,0.187,1.7,-0.6,1.1,2.0
3,Steven Adams,True,17.0,2019.0,C,25.0,OKC,80.0,2669.0,18.5,...,12.6,16.4,5.1,4.0,9.1,0.163,0.7,0.4,1.1,2.1
4,Steven Adams,True,21.0,2020.0,C,26.0,OKC,58.0,1564.0,20.8,...,14.1,17.2,3.7,2.5,6.2,0.190,2.1,1.1,3.2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2581,Malik Newman,NaN,447.0,2020.0,SG,22.0,CLE,1.0,4.0,-11.3,...,25.8,41.5,0.0,0.0,0.0,-0.503,-14.5,-11.3,-25.9,0.0
2582,Jeremy Pargo,NaN,449.0,2020.0,PG,33.0,GSW,3.0,44.0,12.7,...,15.1,25.7,0.0,0.0,0.0,0.011,-2.8,-3.1,-5.9,0.0
2583,Brian Bowen,NaN,471.0,2020.0,SG,21.0,IND,5.0,29.0,-2.0,...,10.0,15.2,-0.1,0.0,-0.1,-0.154,-9.7,-2.1,-11.8,-0.1
2584,Zach Norvell,NaN,490.0,2020.0,SG,22.0,TOT,5.0,41.0,2.6,...,19.4,16.1,-0.1,0.0,-0.1,-0.084,-7.1,-1.2,-8.3,-0.1
2585,Luka Šamanic,NaN,493.0,2020.0,PF,20.0,SAS,1.0,12.0,-3.4,...,0.0,14.5,-0.1,0.0,-0.1,-0.252,-7.4,-4.5,-11.9,0.0

In [63]:
clean_active_ps = merged_ps.dropna(how="any")
clean_active_ps

,Player,is_active,Rank (WS),Year,Pos,Age,Tm,G,MP,PER,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Steven Adams,True,44.0,2016.0,C,22.0,OKC,80.0,2014.0,15.5,...,14.1,12.6,4.2,2.3,6.5,0.155,0.0,0.2,0.2,1.1
1,Steven Adams,True,47.0,2017.0,C,23.0,OKC,80.0,2389.0,16.5,...,16.0,16.2,3.3,3.1,6.5,0.130,-0.2,0.0,-0.2,1.1
2,Steven Adams,True,15.0,2018.0,C,24.0,OKC,76.0,2487.0,20.6,...,13.3,16.7,6.7,3.0,9.7,0.187,1.7,-0.6,1.1,2.0
3,Steven Adams,True,17.0,2019.0,C,25.0,OKC,80.0,2669.0,18.5,...,12.6,16.4,5.1,4.0,9.1,0.163,0.7,0.4,1.1,2.1
4,Steven Adams,True,21.0,2020.0,C,26.0,OKC,58.0,1564.0,20.8,...,14.1,17.2,3.7,2.5,6.2,0.190,2.1,1.1,3.2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601,Cody Zeller,True,102.0,2020.0,C,27.0,CHO,58.0,1341.0,18.8,...,11.9,20.8,2.4,1.2,3.6,0.129,0.2,-0.8,-0.6,0.5
1603,Ivica Zubac,True,301.0,2017.0,C,19.0,LAL,38.0,609.0,17.0,...,10.4,20.3,0.6,0.5,1.1,0.086,-1.2,-0.6,-1.7,0.0
1604,Ivica Zubac,True,305.0,2018.0,C,20.0,LAL,43.0,410.0,15.3,...,15.3,17.6,0.5,0.5,1.0,0.118,-1.8,-0.3,-2.0,0.0
1605,Ivica Zubac,True,148.0,2019.0,C,21.0,TOT,59.0,1040.0,18.9,...,13.9,20.3,1.9,1.3,3.2,0.148,-0.2,-0.2,-0.5,0.4
1606,Ivica Zubac,True,31.0,2020.0,C,22.0,LAC,64.0,1156.0,21.0,...,11.8,16.2,3.6,2.0,5.6,0.231,1.5,1.0,2.5,1.3

In [67]:
#reading in player salary xlsx file

playerSalary = pd.read_excel("Player_Salary.xlsx")
playerSalary2 = playerSalary.rename(columns={"NAME":"Player"})
playerSalary2.head()

   RK             Player Position                   TEAM    SALARY
0   1      Stephen Curry       PG  Golden State Warriors  40231758
1   2         Chris Paul       PG  Oklahoma City Thunder  38506482
2   3  Russell Westbrook       PG        Houston Rockets  38506482
3   4          John Wall       PG     Washington Wizards  38199000
4   5       Kevin Durant       SF          Brooklyn Nets  38199000

In [68]:
#Merging player salary with active player dataframe
APS = pd.merge(clean_active_ps,playerSalary2,on="Player",how="outer")
ActivePlayerStats = APS.dropna(how = "any")
ActivePlayerStats

,Player,is_active,Rank (WS),Year,Pos,Age,Tm,G,MP,PER,...,WS,WS/48,OBPM,DBPM,BPM,VORP,RK,Position,TEAM,SALARY
0,Steven Adams,True,44.0,2016.0,C,22.0,OKC,80.0,2014.0,15.5,...,6.5,0.155,0.0,0.2,0.2,1.1,41.0,C,Oklahoma City Thunder,25842697.0
1,Steven Adams,True,47.0,2017.0,C,23.0,OKC,80.0,2389.0,16.5,...,6.5,0.130,-0.2,0.0,-0.2,1.1,41.0,C,Oklahoma City Thunder,25842697.0
2,Steven Adams,True,15.0,2018.0,C,24.0,OKC,76.0,2487.0,20.6,...,9.7,0.187,1.7,-0.6,1.1,2.0,41.0,C,Oklahoma City Thunder,25842697.0
3,Steven Adams,True,17.0,2019.0,C,25.0,OKC,80.0,2669.0,18.5,...,9.1,0.163,0.7,0.4,1.1,2.1,41.0,C,Oklahoma City Thunder,25842697.0
4,Steven Adams,True,21.0,2020.0,C,26.0,OKC,58.0,1564.0,20.8,...,6.2,0.190,2.1,1.1,3.2,2.0,41.0,C,Oklahoma City Thunder,25842697.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,Cody Zeller,True,102.0,2020.0,C,27.0,CHO,58.0,1341.0,18.8,...,3.6,0.129,0.2,-0.8,-0.6,0.5,88.0,C,Charlotte Hornets,14471910.0
1559,Ivica Zubac,True,301.0,2017.0,C,19.0,LAL,38.0,609.0,17.0,...,1.1,0.086,-1.2,-0.6,-1.7,0.0,181.0,C,LA Clippers,6481482.0
1560,Ivica Zubac,True,305.0,2018.0,C,20.0,LAL,43.0,410.0,15.3,...,1.0,0.118,-1.8,-0.3,-2.0,0.0,181.0,C,LA Clippers,6481482.0
1561,Ivica Zubac,True,148.0,2019.0,C,21.0,TOT,59.0,1040.0,18.9,...,3.2,0.148,-0.2,-0.2,-0.5,0.4,181.0,C,LA Clippers,6481482.0
1562,Ivica Zubac,True,31.0,2020.0,C,22.0,LAC,64.0,1156.0,21.0,...,5.6,0.231,1.5,1.0,2.5,1.3,181.0,C,LA Clippers,6481482.0

In [54]:
#Reading in Team Stats excel file
workbook = "2016-2020 Regular Season Team Stats.xlsx"
all_dfs = pd.read_excel(workbook, sheet_name = None)

#concatonating sheets to single dataframe
ts_df = pd.concat(all_dfs, ignore_index = True)

#dropping NaN
ts_df.dropna(axis=1, how = "any")

,TEAM,Year,GP,W,L,MIN,OFFRTG,DEFRTG,NETRTG,AST%,AST/TO,AST,OREB%,DREB%,REB%,TOV%,EFG%,TS%,PACE,PIE
0,Atlanta Hawks,2016,82,48,34,3966,104.6,100.8,3.9,66.3,1.71,19.0,23.4,69.8,47.4,15.2,51.6,55.2,97.63,52.8
1,Boston Celtics,2016,82,48,34,3956,105.8,102.5,3.3,61.6,1.76,17.4,29.0,70.7,49.5,13.8,48.8,53.1,99.43,52.0
2,Brooklyn Nets,2016,82,21,61,3951,102.4,109.7,-7.4,58.3,1.51,17.0,27.9,71.6,49.4,15.3,49.2,52.7,96.12,46.0
3,Charlotte Hornets,2016,82,48,34,3971,106.4,103.7,2.7,58.6,1.73,16.7,24.4,75.4,49.9,12.9,50.2,54.5,96.24,51.1
4,Chicago Bulls,2016,82,42,40,3981,104.1,105.5,-1.4,59.1,1.64,17.0,29.0,71.4,50.6,14.2,48.7,52.6,96.60,49.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Sacramento Kings,2020,64,28,36,3102,109.0,110.8,-1.7,58.0,1.62,17.3,25.6,73.5,49.0,14.4,53.1,56.3,99.08,47.8
146,San Antonio Spurs,2020,63,27,36,3059,111.3,112.8,-1.5,58.4,2.00,17.9,22.8,75.1,49.1,12.1,52.9,56.9,100.60,49.8
147,Toronto Raptors,2020,64,46,18,3092,111.3,104.9,6.4,62.6,1.76,18.2,25.9,71.5,49.4,14.2,53.6,57.4,100.87,53.1
148,Utah Jazz,2020,64,41,23,3077,112.1,108.8,3.3,55.2,1.49,16.7,25.8,74.7,51.2,15.0,55.2,58.7,98.95,51.8
149,Washington Wizards,2020,64,24,40,3087,111.1,115.0,-3.9,60.4,1.80,17.8,26.0,70.8,47.6,13.5,52.8,56.8,103.52,47.8

In [ ]:
#getting max win share by position